// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	proto "github.com/bibit/microservice/proto"
	mock "github.com/stretchr/testify/mock"
)

// MovieHandlerServer is an autogenerated mock type for the MovieHandlerServer type
type MovieHandlerServer struct {
	mock.Mock
}

// GetListMovie provides a mock function with given fields: _a0, _a1
func (_m *MovieHandlerServer) GetListMovie(_a0 context.Context, _a1 *proto.ListMovieRequest) (*proto.MovieList, error) {
	ret := _m.Called(_a0, _a1)

	var r0 *proto.MovieList
	if rf, ok := ret.Get(0).(func(context.Context, *proto.ListMovieRequest) *proto.MovieList); ok {
		r0 = rf(_a0, _a1)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*proto.MovieList)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *proto.ListMovieRequest) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
